AllCops:
  Include:
    - Rakefile
    - lib/**/*
    - spec/**/*
  Exclude:
    - .*/**/*
    - .**/*
    - test/**/*

LineLength:
  Max: 90

Style/SignalException:
  EnforcedStyle: 'only_raise'

Metrics/MethodLength:
  CountComments: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing
