language: ruby

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - jruby-19mode
  - rbx-2

script:
  - bundle exec rspec spec
  - bundle exec rake test
  - bundle exec rake test:integration

services:
  - redis
  - rabbitmq

addons:
  postgresql: "9.4"
